"""Small hand-built corpus. Each doc is (id, title, text)."""

DOCS = [
    ("d01", "Photosynthesis", "Plants convert sunlight, water and carbon dioxide into glucose and oxygen. Chlorophyll in the chloroplasts absorbs light energy to drive the reaction."),
    ("d02", "Cellular respiration", "Cells break down glucose with oxygen to release energy stored as ATP. The mitochondria carry out most of this process in eukaryotes."),
    ("d03", "The water cycle", "Water evaporates from oceans and lakes, condenses into clouds, and returns to the surface as rain or snow before running back to the sea."),
    ("d04", "Plate tectonics", "The rigid outer shell of the Earth is broken into plates that drift over the mantle. Their collisions build mountains and cause earthquakes."),
    ("d05", "Volcanoes", "Magma rising through weaknesses in the crust erupts as lava, ash and gas. Most volcanoes sit along plate boundaries or over hotspots."),
    ("d06", "Gradient descent", "An optimizer repeatedly steps in the direction of steepest descent of a loss function. The learning rate controls how large each step is."),
    ("d07", "Overfitting", "A model that memorises its training data performs badly on new examples. Regularisation, more data and early stopping all reduce this gap."),
    ("d08", "Cross validation", "Splitting data into k folds and training k times gives a more reliable estimate of generalisation error than a single holdout split."),
    ("d09", "Neural networks", "Layers of weighted sums followed by nonlinear activations compose to approximate complex functions. Weights are learned by backpropagation."),
    ("d10", "Word embeddings", "Words are mapped to dense vectors so that similar meanings land near each other. Distances in this space capture semantic relationships."),
    ("d11", "Transformers", "Self attention lets every token attend to every other token in a sequence, replacing recurrence and making training highly parallel."),
    ("d12", "Tokenization", "Text is split into subword units before a model sees it. Byte pair encoding merges frequent character pairs to build the vocabulary."),
    ("d13", "TCP and IP", "IP routes packets between hosts while TCP adds ordering, retransmission and flow control to give applications a reliable byte stream."),
    ("d14", "DNS", "The domain name system translates human readable names into IP addresses using a hierarchy of delegated nameservers and cached answers."),
    ("d15", "HTTP caching", "Response headers tell clients and proxies how long a resource may be reused, cutting latency and load on the origin server."),
    ("d16", "SQL indexes", "An index is a sorted structure that lets the database find rows without scanning the whole table, at the cost of slower writes."),
    ("d17", "Database transactions", "A transaction groups statements so they either all commit or all roll back, preserving invariants even when failures interrupt the work."),
    ("d18", "Normalization", "Splitting tables to remove redundant data avoids update anomalies, though heavy joins sometimes justify denormalising for read speed."),
    ("d19", "Garbage collection", "A runtime reclaims memory that the program can no longer reach, freeing the developer from manual deallocation but adding pauses."),
    ("d20", "Concurrency and parallelism", "Concurrency structures a program as independent tasks; parallelism actually runs them at the same time on multiple cores."),
    ("d21", "Version control", "A distributed version control system records snapshots of a project so changes can be reviewed, merged and reverted across many contributors."),
    ("d22", "Continuous integration", "Every push triggers an automated build and test run, catching breakage early instead of at release time."),
    ("d23", "Docker containers", "A container packages an application with its dependencies into an isolated process that runs the same way on any host."),
    ("d24", "Public key cryptography", "A keypair lets anyone encrypt a message with the public half while only the holder of the private half can decrypt or sign."),
    ("d25", "Password hashing", "Storing a slow salted hash instead of the password itself means a stolen database does not immediately reveal user credentials."),
    ("d26", "TLS handshake", "Client and server agree on a cipher, verify a certificate chain, and derive session keys before any application data is sent."),
    ("d27", "The Roman Republic", "Rome was governed by elected magistrates and a senate for centuries before civil wars gave way to rule by emperors."),
    ("d28", "The Industrial Revolution", "Steam power, factories and railways transformed production and moved populations from farms into rapidly growing cities."),
    ("d29", "The printing press", "Movable type made books cheap enough to spread literacy and ideas far faster than hand copying ever allowed."),
    ("d30", "Antibiotics", "Compounds that kill or halt bacteria revolutionised medicine, but overuse selects for resistant strains that no longer respond."),
    ("d31", "Vaccination", "Exposing the immune system to a harmless piece of a pathogen trains it to respond quickly to a real infection later."),
    ("d32", "The human genome", "Roughly three billion base pairs encode the instructions for building and running a human body, only a fraction of it coding for proteins."),
    ("d33", "Black holes", "A region where gravity is so strong that nothing, not even light, escapes. Its boundary is called the event horizon."),
    ("d34", "The expanding universe", "Distant galaxies recede faster the further away they are, evidence that space itself has been stretching since the big bang."),
    ("d35", "Orbital mechanics", "A satellite stays in orbit because its sideways velocity keeps it falling around the planet rather than into it."),
    ("d36", "Supply and demand", "Prices settle where the quantity buyers want matches the quantity sellers offer; shifts in either curve move the equilibrium."),
    ("d37", "Inflation", "A sustained rise in the general price level reduces what each unit of currency buys, often driven by money supply or supply shocks."),
    ("d38", "Compound interest", "Interest earned is added to the principal so future interest is calculated on a larger base, making growth exponential over time."),
    ("d39", "Sorting algorithms", "Comparison sorts like merge sort and quicksort run in n log n time, while counting sort exploits bounded keys to do better."),
    ("d40", "Big O notation", "A way to describe how the running time or memory of an algorithm grows as the input size increases, ignoring constant factors."),
]
